### PR TITLE
feat: ✨ Update packages to latest versions

### PR DESCRIPTION
**Pull request by schilchSICKAG**
# Pull Request

## 📖 Description

This PR updates all packages to the latest version range. It also adds:

- [x] support for Angular@19
- [x] Updates our Angular demo to use the new major angular version.
- [x] Update Shoelace to 2.18.0

### 🎫 Issues

Closes #258 

## 👩‍💻 Reviewer Notes

Just have a look at the build outputs and play around with the demos as usual.

## 📑 Test Plan

Check out the branch and make sure to have the latest playwright images installed (e.g. run `pnpm exec playwright install` in either the components or e2e packages).

## ✅ DoD

- [x] I have tested my changes manually.
- [ ] ~~I have added automatic tests for my changes (unit- and visual regression tests).~~
- [x] I have updated the project documentation to reflect my changes (e.g. CHANGELOG, Storybook, ...).
- [ ] ~~I have added documentation to the DaVinci migration guide (if need be)~~
- [x] I have made sure to follow the projects coding and contribution guides.
- [ ] ~~I have made sure that the bundle size has changed appropriately.~~
- [x] I have validated that there are no accessibility errors.
- [ ] ~~I have used design tokens instead of fix css values~~

### CODE REVIEW

**Comment by kirchsuSICKAG** [comment]
We should add angular version 19 to our supported angular versions in the documentation (file `README.md`of angular wrapper) : 
image

**Comment by schilchSICKAG** [comment]
> We should add angular version 19 to our supported angular versions in the documentation

Done :)

**Comment by kirchsuSICKAG** [comment]
Since the update the `pnpm type-check` does not longer work in the `vue-demo` project
see: 
Bildschirmfoto 2024-11-27 um 14 55 42

**Comment by schilchSICKAG** [comment]
> Since the update the `pnpm type-check` does not longer work in the `vue-demo`

This seems to be a known issue with vue-tsc and typescript version 5.7.2. I opted to use typescript@5.6.2 for the time being until this is fixed by providing the specifier as `"typescript": "~5.6.2"`. This makes sure that it will work for the time being.

**Pull request merged**
